# Generated by Django 4.2.4 on 2024-01-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=10000)),
                ('tech', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlogo', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(blank=True, default=None, max_length=300)),
                ('cerlogo', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('cerimg', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('experience', models.CharField(blank=True, max_length=10)),
                ('project', models.CharField(blank=True, default=None, max_length=1000)),
                ('achievement', models.CharField(blank=True, default=None, max_length=100)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.technology')),
            ],
        ),
        migrations.CreateModel(
            name='serviceattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=1000)),
                ('att_of', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='content.service')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField(auto_now_add=True)),
                ('timeframe', models.TextField(max_length=50)),
                ('goals', models.TextField(max_length=2000)),
                ('questions', models.TextField(max_length=2000)),
                ('audience', models.TextField(max_length=1000)),
                ('status', models.TextField(max_length=300)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.service')),
            ],
        ),
    ]
