# Generated by Django 4.2.4 on 2024-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_education_alter_social_logo_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeline', models.CharField(max_length=300)),
                ('objectives', models.CharField(max_length=3000)),
                ('questions', models.CharField(max_length=3000)),
                ('audience', models.CharField(max_length=3000)),
            ],
        ),
    ]
